### ISSUE TITLE
CASA crashes when trying to fit

### ISSUE THREAD

**Issue by masolimano** [onsala-space-observatory/UVMultiFit#3]
Hello,
I installed UVMultiFit on a CentOS7 machine, using CASA version 5.4, following the instructions given in the INSTALL file.

I am trying to run the test suite using the `TEST_ALL.py` script. The simulations run fine, and the loading of the scans too but then it just crashes. I think I'm getting a seg-fault but the log doesn't print anything useful. I attach the .dmp and .txt files generated by the CrashReporter for the `Disc/Disc.alma.out10.noisy.ms`, hoping they contain a hint of what went wrong.

[f593c6d1-3e45-4bd2-92b241b8-d591513.tar.gz](https://github.com/onsala-space-observatory/UVMultiFit/files/4731584/f593c6d1-3e45-4bd2-92b241b8-d591513.tar.gz)

Best regards,
Manuel.

**Comment by molberg** [comment]
Hi @masolimano,
Could you use the attached `setup.py` file and rebuild the UVMultiFit module? You will notice it has a variable defining the root folder of your casa installation, this will make sure the module is built with the same numpy version as the one used by casa and which may be different than the one that came with CentOS7. Note, that I needed to add an extra .txt extension, so that github would accept the file. You will need to rename it back to `setup.py`

[setup.py.txt](https://github.com/onsala-space-observatory/UVMultiFit/files/4751735/setup.py.txt)

**Comment by masolimano** [comment]
Hi @molberg 
As you might have guessed, my installation was compiled with the wrong numpy api. I got the warning message while trying to run the tests (see log file attached).

The setup.py file you provide makes the compiler to grab the correct header file, and now it works! I can run the test suite without CASA crashing :)

Haven't checked the results to see if they make sense though, but anyway I thinks this was the whole issue.

Thanks for your time! I guess the installation instructions should cover this.

[uvmultifit.log](https://github.com/onsala-space-observatory/UVMultiFit/files/4761816/uvmultifit.log)

**Comment by molberg** [comment]
Hi @masolimano 
Thanks for closing the issue. I have pushed an updated `setup.py` file and and added instructions to the `INSTALL.md` file on how to adapt that script to a user's `casa` installation. 
P.S: I like your avatar, especially the background. The SEST was my work place 1986-1989, i.e. during construction and first years of operations!

**Comment by masolimano** [comment]
You are welcome, thank you for the help.

Glad you liked my avatar pic. It is from the eclipse event at La Silla last year. SEST is such a cool and photogenic antenna, even from the rear! Love how you can see your reflection on its shiny surface if you stand at the right spot :)
